[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://event-reg-backend.herokuapp.com 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-VWe8j+sQ9/RHQM6TyGioNGksvqVhRHLokKrbzUKYG1w=';"
